sudo: required
language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=bionic
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -Wpedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

cache:
  directories:
    - ${DEPS_DIR}

compiler:
  - gcc
  - clang

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then

      # Download and install recent cmake
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

      # Install conan
      pip install conan

      # Sets libcxx to C++11 ABI
      conan profile new default --detect
      conan profile update settings.compiler.libcxx=libstdc++11 default  
    fi

before_script:
  - rm -rf build
  - mkdir build
  - cd build

script:
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
  - conan install .. -s build_type=Debug --build=missing
  - conan install .. -s build_type=Release --build=missing
  - make -j

notifications:
  email: false